### ISSUE TITLE
Обновления гайда

### ISSUE THREAD

**Issue by yurapanasyuk** [kupibilet-frontend/ui#107]
-----

- [ ] **Внести коретировки по адаптивной типографике для h1 и h2**
http://take.ms/NqoS9i как указано тут
-----

- [ ] **Добавить инпут-форму, как компонент**
https://projects.invisionapp.com/d/main#/console/10728011/228527791/preview
-----

- [ ] **Обновить цвет заголовков**
Цвет h1 — h6, uppercase  16, uppercase 20 заменить на gray-darkest
При этом надо обновить константы цветов

-----

- [ ] **Добавить болд**
Добавить болд в типографику. Болдом могут быть h1—h5
Это значит, что мы по месту выбираем или семиболд или болд. Стандартизирование будет ухудшать расстановку акцентов. Приходится варировать
-----

- [ ] **Изменения в цветовых константах**
Обновились:
— orange-lightest на FFF5C7 с FFF0BF
— blue-lightest на E8F7FF с E5F5FF
— gray-darkest на 111111 с 222222
> @yurapanasyuk Напиши какими они были раньше
> @7rulnik Написал

-----

- [x] **Новые константы расстояний**
От 4xl до 8xl

> @yurapanasyuk Мы их не используем

-----

- [ ] **Добавились константы радиуса скругления**
— 12 px
— 24 px

-----

- [ ] **Изменилась прозрачность на 0.5 у тени shadow-small**
0 3px 9px -1px rgba(98,112,139,.5)

> @yurapanasyuk Нужно посмотреть где она используется.
> Сейчас это только выпадающий список Autocomplete и Dropdown.
> Возможно, там должна быть другая тень (хотя я против  использования shadowLarge где-либо)

-----

- [x] **Изменилось поведение кнопок** (#145)
— При наведении меняется фон на более темный и добавляется бордер + убрать анимацию
— При нажатии фон ещё более тёмный, бордер убирается
— Анимируется только при отведении мыши

-----

- [x] **Добавилась Secondary Button** (#145)
Все такое же, как у синей, отличаются только цвета фона и бордера

-----

- [ ] **Tumblr и Slider**
— При наведении у точки появляется тень shadow-small
— У выбранного тумблера изменился цвет подложки на A9DDFF

-----

**Гайд**
https://projects.invisionapp.com/d/main/default/#/projects/prototypes/10728011

**Comment by nezed** [comment]
@yurapanasyuk Видимо, цвета про которые ты говорил, раньше были 
- `secondaryLightest: '#fff0bf'`
- `primaryLightest: '#e5f5ff'`

Не забудь про остальные вопросы в этом ишью

**Comment by toshafed** [comment]
Закрыл т.к. неактуально
