### ISSUE TITLE
Обновить стиль заголовка в модулях на букинге

### ISSUE THREAD

**Issue by yurapanasyuk** [kupibilet-frontend/ui#130]
![image](https://user-images.githubusercontent.com/29432172/29454219-fecc8f0a-8414-11e7-8352-477ae1e5e02f.png)

Это стиль заголовка меняется на H4

![image](https://user-images.githubusercontent.com/29432172/29454245-1bc5a5ce-8415-11e7-8681-6fdb728024ea.png)

По гайду:
https://projects.invisionapp.com/d/main/default/#/console/10728011/228527789/preview

![image](https://user-images.githubusercontent.com/29432172/29454184-e246bd6a-8414-11e7-8699-880327495e31.png)

на 
 
![image](https://user-images.githubusercontent.com/29432172/29454199-f510c6d4-8414-11e7-88b6-4df87cccfa23.png)

Обновлены только три макета:
https://projects.invisionapp.com/d/main/default/#/console/10596875/234410958/preview
https://projects.invisionapp.com/d/main/default/#/console/10596875/225446903/preview
https://projects.invisionapp.com/d/main/default/#/console/10596875/242681750/preview

В остальных местах может встречаться старый стиль.

**Comment by nezed** [comment]
@Azein Это, видимо, тебе напоминашка

**Comment by nezed** [comment]
@Azein Насколько я понимаю, в основном проекте уже выбраны правильные заголовки, и это ишью можно закрыть?

**Comment by nezed** [comment]
Перенесено в #146
