### ISSUE TITLE
Оценить уместность FormItem

### ISSUE THREAD

**Issue by nezed** [kupibilet-frontend/ui#133]
Необходимо проанализировать почему появился и какие задачи способен решить.
По итогу либо удалить, либо переименовать.

**Comment by nezed** [comment]
@Azein Займёшься?

**Comment by Azein** [comment]
Сейчас гляну. У меня он используется, т.к. я считал что это уже принятый подход.

**Comment by nezed** [comment]
@Azein Это стоит сохранить как примитив?

**Comment by Azein** [comment]
По сути, этот компонент просто оборачивает children в див, и ставит стайлед лейбл. Можно переименовать, т.к. лейблы проставлять надо, а инпут и так уже несколько перегружен функционалом и условиями рендеринга

**Comment by nezed** [comment]
@7rulnik @toshafed  Как насчёт переименовать в `<WithLabel label="" htmlFor="" />`?
Сейчас этот `FormItem` используется в ветке нового букинга, это будет breaking, но не серьёзный

**Comment by Azein** [comment]
Так это, что решаем-то? =)

**Comment by nezed** [comment]
Это говно всё ещё цветет и пахнет с всё большим размахом)) Давно пора было делать переезд) Но… Говно всё ещё пахнет
