### ISSUE TITLE
Селект не закрывается при нажатии на стрелку

### ISSUE THREAD

**Issue by toshafed** [kupibilet-frontend/ui#161]
Hi, guys! We here in Russia are very pleased with your lib! 
But your select does not close properly

Vidos v attache
[select.zip](https://github.com/kupibilet-frontend/ui/files/1362178/select.zip)

**Comment by nezed** [comment]
@Azein

**Comment by Azein** [comment]
Issue should be fixed with https://github.com/kupibilet-frontend/ui/pull/163
