### ISSUE TITLE
Телепортация крестика в Modal на десктопе

### ISSUE THREAD

**Issue by privetkometa** [kupibilet-frontend/ui#183]
при открытии модального окна на десктопе крестик сначала в модалке справа сверху, а потом уже телепортируется на оверлей

**Comment by nezed** [comment]
Воспроизводится в сторибуке
https://kupibilet-frontend.github.io/ui/?selectedKind=Complex%20controls%2FModal&selectedStory=Default

**Comment by 7rulnik** [comment]
@nezed @privetkometa я так понимаю закрыли в https://github.com/kupibilet-frontend/ui/pull/190 ?

**Comment by privetkometa** [comment]
@7rulnik да
