### ISSUE TITLE
prepush вместо precommit

### ISSUE THREAD

**Issue by 7rulnik** [kupibilet-frontend/ui#55]

**Comment by 7rulnik** [comment]
@nezed я боюсь, ты поторопился. Ты можешь закоммитить несколько раз, а lint-staged ничего не увидит, т.к. ищет именно в стейдже файлы. Я прав?

**Comment by nezed** [comment]
@7rulnik Капитально поторопился.
Похоже линтить последний коммит - задача до сих пор не решенная лучше, чем в основном проекте, оставил пока так 	687836a

**Comment by 7rulnik** [comment]
Угу. По идее нам надо сделать что-то подобное https://github.com/mcwhittemore/staged-git-files только для диффа веток. Скриптик у нас есть для этого уже, да. И в lint-staged как-нибудь это пропихнуть было бы круто, конечно.
