### ISSUE TITLE
Обновить парсер svg-иконок

### ISSUE THREAD

**Issue by yurapanasyuk** [kupibilet-frontend/ui#56]
Поменялся механизм экспорта иконок в SVG. Нужно, чтобы можно было юзать новые.

**Comment by nezed** [comment]
@toshafed в курсе в чем дело?

**Comment by 7rulnik** [comment]
@toshafed @s-kobets я так понимаю уже всё сделали и можно закрыть?

**Comment by toshafed** [comment]
да
