### ISSUE TITLE
Кривой импорт rc-tabs

### ISSUE THREAD

**Issue by 7rulnik** [kupibilet-frontend/ui#63]
Одновременно импортится и es6 версия и es5. @s-kobets у тебя там, кажется, косяк в импортах.

![image](https://user-images.githubusercontent.com/5969049/27248627-11719330-530f-11e7-943a-fb9faff8bf4f.png)

**Comment by s-kobets** [comment]
https://github.com/kupibilet-frontend/ui/pull/65/commits/be358fa28dbc8ac71fd557188de17dcc5cdf3885

**Comment by nezed** [comment]
Closed by #65
