### ISSUE TITLE
Tree shaking VS relative imports

### ISSUE THREAD

**Issue by nezed** [kupibilet-frontend/ui#76]
Так же необходимо убрать из main файла с es-modules экспортами утилиты
[src/index.js:30-31](https://github.com/kupibilet-frontend/ui/blob/v2.3.0/src/index.js#L30-L31)

**Comment by 7rulnik** [comment]
https://github.com/lodash/babel-plugin-lodash умеет вот так вот:

```js
{
  "plugins": [["lodash", { "id": "@kupibilet/ui", "cwd": "some/path" }]],
}
```

**Comment by nezed** [comment]
Resolved by #111
